---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 18.17.0

inputs:
  - name: sixteens

outputs:
  - name: build

run:
  path: sixteens/ci/scripts/build.sh
