name: CI

permissions:
  contents: read

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  audit-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install --unsafe-perm
      - name: Run npm audit
        env:
          OSSINDEX_USERNAME: ${{ secrets.OSSINDEX_USERNAME }}
          OSSINDEX_TOKEN: ${{ secrets.OSSINDEX_TOKEN }}
        run: npm run audit

  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install --unsafe-perm
      - name: Run build test
        run: npm run build
